
/* Autogenerated file, do not edit! */

/* eslint-disable */
import {
  type AbiType,
  AztecAddress,
  type AztecAddressLike,
  CompleteAddress,
  Contract,
  type ContractArtifact,
  ContractBase,
  ContractFunctionInteraction,
  type ContractInstanceWithAddress,
  type ContractMethod,
  type ContractStorageLayout,
  type ContractNotes,
  decodeFromAbi,
  DeployMethod,
  EthAddress,
  type EthAddressLike,
  EventSelector,
  type FieldLike,
  Fr,
  type FunctionSelectorLike,
  loadContractArtifact,
  loadContractArtifactForPublic,
  type NoirCompiledContract,
  NoteSelector,
  Point,
  type PublicKey,
  PublicKeys,
  type Wallet,
  type U128Like,
  type WrappedFieldLike,
} from '@aztec/aztec.js';
import AccountBasedPrivacyContractArtifactJson from '../../target/AccountBasedPrivacy-AccountBasedPrivacy.json' with { type: 'json' };
export const AccountBasedPrivacyContractArtifact = loadContractArtifact(AccountBasedPrivacyContractArtifactJson as NoirCompiledContract);


      export type Transfer = {
        sender: AztecAddressLike
recipient: AztecAddressLike
amount: (bigint | number)
embedded_amount_nonce: FieldLike
      }
    

/**
 * Type-safe interface for contract AccountBasedPrivacy;
 */
export class AccountBasedPrivacyContract extends ContractBase {
  
  private constructor(
    instance: ContractInstanceWithAddress,
    wallet: Wallet,
  ) {
    super(instance, AccountBasedPrivacyContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A promise that resolves to a new Contract instance.
   */
  public static async at(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    return Contract.at(address, AccountBasedPrivacyContract.artifact, wallet) as Promise<AccountBasedPrivacyContract>;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, ) {
    return new DeployMethod<AccountBasedPrivacyContract>(PublicKeys.default(), wallet, AccountBasedPrivacyContractArtifact, AccountBasedPrivacyContract.at, Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, ) {
    return new DeployMethod<AccountBasedPrivacyContract>(publicKeys, wallet, AccountBasedPrivacyContractArtifact, AccountBasedPrivacyContract.at, Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof AccountBasedPrivacyContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<AccountBasedPrivacyContract['methods'][M]>
  ) {
    return new DeployMethod<AccountBasedPrivacyContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      AccountBasedPrivacyContractArtifact,
      AccountBasedPrivacyContract.at,
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return AccountBasedPrivacyContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(AccountBasedPrivacyContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'received_amounts' | 'spent_amounts'> {
      return {
        received_amounts: {
      slot: new Fr(1n),
    },
spent_amounts: {
      slot: new Fr(2n),
    }
      } as ContractStorageLayout<'received_amounts' | 'spent_amounts'>;
    }
    

  public static get notes(): ContractNotes<'OneWayNote'> {
    return {
      OneWayNote: {
          id: new NoteSelector(0),
        }
    } as ContractNotes<'OneWayNote'>;
  }
  

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_private_state() */
    sync_private_state: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** transfer(recipient: struct, amount: integer) */
    transfer: ((recipient: AztecAddressLike, amount: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
    public static get events(): { Transfer: {abiType: AbiType, eventSelector: EventSelector, fieldNames: string[] } } {
    return {
      Transfer: {
        abiType: {
    "kind": "struct",
    "fields": [
        {
            "name": "sender",
            "type": {
                "kind": "struct",
                "fields": [
                    {
                        "name": "inner",
                        "type": {
                            "kind": "field"
                        }
                    }
                ],
                "path": "aztec::protocol_types::address::aztec_address::AztecAddress"
            }
        },
        {
            "name": "recipient",
            "type": {
                "kind": "struct",
                "fields": [
                    {
                        "name": "inner",
                        "type": {
                            "kind": "field"
                        }
                    }
                ],
                "path": "aztec::protocol_types::address::aztec_address::AztecAddress"
            }
        },
        {
            "name": "amount",
            "type": {
                "kind": "integer",
                "sign": "unsigned",
                "width": 128
            }
        },
        {
            "name": "embedded_amount_nonce",
            "type": {
                "kind": "field"
            }
        }
    ],
    "path": "AccountBasedPrivacy::Transfer"
},
        eventSelector: EventSelector.fromString("0xdd6d9697"),
        fieldNames: ["sender","recipient","amount","embedded_amount_nonce"],
      }
    };
  }
  
}
